BeyondTrust/terraform-provider-passwordsafe

CHANGELOG.md, SECURITY.md, docs/index.md, terraform/main.tf
Files added:
CHANGELOG.md
SECURITY.md
Files modify:
main.tf
=> documentation modify and added

.github/workflows/promotion.yml
Promotion action working to promote artifacts to any repository
=> Promotion action

.github/dependabot.yml
=> dependabot.yml added

.frogbot/frogbot-config.yml, .github/workflows/frogbot.yml, README.md, go.mod
https://beyondtrust.atlassian.net/browse/BIPS-13576
=> Feat: Frogbot implementation & build step fixed

.github/workflows/release.yml, .github/workflows/sonarqube.yml
https://beyondtrust.atlassian.net/browse/BIPS-13723
=> Feat: Sonarqube added

.github/workflows/enforce-pr-issue-link.yml, .github/workflows/frogbot.yml
Create a workflow to enforce linking the Jira story to the PR (`enforce-pr-issue-link.yml`)
Ticket: https://beyondtrust.atlassian.net/browse/BIPS-15405
=> feat: BIPS-15405 Enforce PR link to Jira

.github/workflows/golint.yml, .golangci.yml
According to ticket [BIPS-22586](https://beyondtrust.atlassian.net/browse/BIPS-22586)
[BIPS-22586]: https://beyondtrust.atlassian.net/browse/BIPS-22586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: adding go linter

.github/workflows/promotion.yml, .github/workflows/release.yml
Release & Promotion workflow refactored working with new version format
[BIPS-23044](https://beyondtrust.atlassian.net/browse/BIPS-23044)
Summary of changes:
- Promotion workflow refactored.
- Release workflow refactored in order to build new artifacts accoding to new build number format.
- Unit testing running ok after changing target folder
[BIPS-23044]: https://beyondtrust.atlassian.net/browse/BIPS-23044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CI: [BIPS-23044] Release & Promotion workflow refactored

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/validate-pr-template.yml
Adding PR template
BIPS-23403
- Creating a PR template.
- Adding PR template workflow validation
=> CI: [BIPS-23403] adding PR template validation

.github/workflows/validate-pr-template.yml
Fixing the PR template validation
BIPS-23403
- Adding condition to check if the PR is created by dependabot or release-please-app
=> CI: adding bots exclusion for PR template validation

.github/workflows/sonarqube.yml
[Integration] Include unitest coverage as comment into the PR
https://beyondtrust.atlassian.net/browse/BIPS-23432
- Adding Unitest code coverage as a comment into the PR
=> CI: [BIPS-23432] Including unitest coverage as comment into the PR

.github/workflows/coverage-report.yml, .github/workflows/sonarqube.yml
[Integration] Include unitest coverage as comment into the PR
https://beyondtrust.atlassian.net/browse/BIPS-23432
- Fixing errors on the implementation of the new workflow.
=> CI: [BIPS-23432] Fixing unitest coverage as comment into the PR

terraform/main.tf
Include API version parameter documentation in terraform example script.
https://beyondtrust.atlassian.net/browse/BIPS-24104
Include API version parameter in main.tf file (sample script)
=> chore: add api version to terraform example file

go.mod, go.sum
Fix plugin crashed - with nonexistent API server
https://beyondtrust.atlassian.net/browse/BIPS-24883
Update go client library version in go.mod file
=> fix: plugin crashed - with nonexistent API server

.github/workflows/release.yml, .goreleaser.yml
Fix deployment for release
[BIPS-25166](https://beyondtrust.atlassian.net/browse/BIPS-25166)
- Update release to work with Goreleaser newest version.
- Update .goreleaser.yml to work with newest version.
- Enable release to build and release new version.
[BIPS-25166]: https://beyondtrust.atlassian.net/browse/BIPS-25166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CI: [BIPS-25166] Build and release steps enable and update to newest version

.github/workflows/golint.yml
Add Cognitive(code) complexity check in workflow
https://beyondtrust.atlassian.net/browse/BIPS-24543
- Adding code cognitive complexity on workflow go lint
=> CI: [BIPS-24543] adding code cognitive completixy check

go.mod, go.sum, providers/provider_framework/managed_systems_by_asset_resource.go, providers/provider_framework/managed_systems_by_database_resource.go, providers/provider_framework/managed_systems_by_database_resource_test.go, providers/provider_framework/managed_systems_by_workgroup_resource.go, providers/provider_framework/provider.go, terraform/main.tf
Add creating Managed System feature associated with Databases in terraform provider - Terraform provider side.
https://beyondtrust.atlassian.net/browse/BIPS-23887
- Include Adding creating Managed System feature associated with Databases in terraform provider.
- Create unit tests for above item.
- Improve main.tf terraform script.
- Include managed_system_name parameter in Managed System resources.
=> feat: add creating Managed System feature associated with Databases

go.mod
Upgrade go version to the latest version (1.24.2).
https://beyondtrust.atlassian.net/browse/BIPS-27241
- Upgrade go version in go.mod file.
=> feat: Upgrade go version to the latest version (1.24.2)

.github/workflows/frogbot.yml, .github/workflows/promotion.yml, .github/workflows/sonarqube.yml
Add Jfrog Artifactory's OIDC on terraform provider repo workflow
[BIPS-26688](https://beyondtrust.atlassian.net/browse/BIPS-26688)
- Release workflow updated
- Promotion workflow updated
- Frogbot workflow updated
[BIPS-26688]: https://beyondtrust.atlassian.net/browse/BIPS-26688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CI: [BIPS-26688] Add Jfrog Artifactory's OIDC on terraform provider repo workflow

.github/workflows/coverage-report.yml, .github/workflows/dependabot-comments.yml, .github/workflows/frogbot.yml, .github/workflows/golint.yml, .github/workflows/release.yml
Massified Dependabot PR comments
[BIPS-27986](https://beyondtrust.atlassian.net/browse/BIPS-27986)
- Dependabot PR Comment workflow added
[BIPS-27986]: https://beyondtrust.atlassian.net/browse/BIPS-27986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CI: [BIPS-27986] Dependabot PR Comment added

.github/workflows/release.yml, .goreleaser.yml
Fix snapshot version for Terraform Providers artifacts 
[BIPS-29859](https://beyondtrust.atlassian.net/browse/BIPS-29859)
- .gorelease.yml updated
- release.yml updated
[BIPS-29859]: https://beyondtrust.atlassian.net/browse/BIPS-29859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ci: [BIPS-29859] Snapshot version fixed
